default_platform(:ios)

platform :ios do

  desc "Run tests on each PR"
  lane :test do
    scan(device: "iPhone 15 Pro")
  end

  desc  "Deploy app to App Store Connect"
  lane :deploy do 
    # match(readonly: true)
    # gym(
    #   export_options: "./fastlane/ExportOptions.plist"
    # )
    # gym
    api_key = app_store_connect_api_key(
      key_id: "V4D62Q8UQB",
      issuer_id: "69a6de92-2bb4-47e3-e053-5b8c7c11a4d1",
      key_content: $APP_STORE_CONNECT_API_KEY_BASE64,
      is_key_content_base64: true
    )
    # deliver(
    #   api_key: api_key,
    #   force: true,
    #   skip_screenshots: true,
    #   precheck_include_in_app_purchases: false
    # )
  end 

end