name: Test
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-13
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Run Unit Tests
        run: fastlane test