name: Test
on:
  push:
    branches: [ test-cache ]
  # pull_request:
  #   branches: [ main ]

jobs:
  test:
    runs-on: self-hosted # macos-13
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-data-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-derived-data-

      # - uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: 15.1

      - name: Run Unit Tests
        run: fastlane test