name: Test
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-13
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.1

      # - uses: actions/cache@v3
      #   with:
      #     path: .build
      #     key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
      #     restore-keys: |
      #       ${{ runner.os }}-spm-
            
      # - uses: actions/cache@v3
      #   with:
      #     path: ~/Library/Developer/Xcode/DerivedData
      #     key: ${{ runner.os }}-derived-data-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-derived-data-

      - name: Run Unit Tests
        run: fastlane test